Nguyen duong
comp129/comp55 pull request #110
Opened 2024-03-08 00:39 UTC by duongnguyen130

Issue: Add Detailed Instructions for Removing Java on Windows and MacOS #109

2024-03-08 01:15 UTC, onzfonz commented
You will need to edit your description to say `Fixes` and then the issue number you provided, just like the canvas assignment states @duongnguyen130

2024-03-08 01:19 UTC, onzfonz requested changes
Please make these changes and edit the description.  You'll need to do one more request for review and I will do another set of changes before this is completed.

2024-03-08 01:19 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +  Respond to the prompts to complete the uninstall
Let's combine these two.
Also, please remove the instructions for Windows 8, 7, Vista & XP.

Also, please place a `- ` before each step

2024-03-08 01:19 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +  [Windows](https://www.java.com/en/download/help/uninstall_java.html)
you'll remove all of these

2024-03-08 01:19 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +4. Or you can check out these instruction.
please add a heading before your section called:

### How to remove Java from your machine

2024-03-08 05:03 UTC, onzfonz requested changes
Please use the add suggestions via batch option to take in these changes
which can be access from the files changed tab in the pull request

![image](https://github.com/comp129/comp55/assets/239024/4b591516-702d-4691-bd5f-c8066d4ecf5a)

You can then re-request a review

2024-03-08 05:03 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +  [Windows](https://www.java.com/en/download/help/uninstall_java.html)
```suggestion
  If you need help, here is
  [further documentation on uninstalling java on Windows](https://www.java.com/en/download/help/uninstall_java.html).
```

2024-03-08 05:03 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +    - Uninstall Oracle Java using the **Terminal**
```suggestion
  ### MacOS
  
  You can uninstall Oracle Java via the ***Terminal***
```

2024-03-08 05:03 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +    - **sudo rm -fr ~/Library/Application\ Support/Oracle/Java**
```suggestion
    - **`sudo rm -fr /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin`**
    - **`sudo rm -fr /Library/PreferencePanes/JavaControlPanel.prefPane`**
    - **`sudo rm -fr ~/Library/Application\ Support/Oracle/Java`**
```

2024-03-08 05:03 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +  [MacOS](https://www.java.com/en/download/help/mac_uninstall_java.html)
```suggestion
  [Further documentation on uninstalling Java on Mac](https://www.java.com/en/download/help/mac_uninstall_java.html)
```

2024-03-08 05:22 UTC, onzfonz commented
@duongnguyen130 you'll need to commit the remaining changes using the add suggestion to batch for the other changes that I presented. At the end, you'll need to use the green commit button to submit

2024-03-08 05:29 UTC, duongnguyen130 reviewed
Solve all suggestions.

2024-03-08 05:36 UTC, onzfonz requested changes
while you made the changes, you did not commit it the way that I was hoping for.  Please fix the errors and then re-request and then I'll review tomorrow.

2024-03-08 17:34 UTC, onzfonz requested changes
Please follow the add suggestions to batch from the files changed tab in this very pull request.  Click files changed

![image](https://github.com/comp129/comp55/assets/239024/07735020-ae75-4bf7-9db6-1a425eab0b64)

Then click add suggestions

![image](https://github.com/comp129/comp55/assets/239024/7b69c100-9526-4a05-8e44-0d4835fa4965)

2024-03-08 17:34 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +To Uninstall via Programs
```suggestion
To uninstall Java via Windows Settings:
```

2024-03-08 17:34 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +You can uninstall Oracle Java via the ***Terminal***
```suggestion
To uninstall Java via Mac's ***Terminal***:
```

2024-03-08 17:35 UTC, onzfonz commented
@duongnguyen130 you'll also need to update the branch here as well

2024-03-21 13:33 UTC, onzfonz requested changes
This won't be approved until you use the add batch feature as suggested above.  If you are not sure what this is, please feel free to message me in order to get this approved.  Let me know if you have any questions about this

2024-03-21 13:33 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +To uninstall Java via Windows Settings:
```suggestion
To uninstall Java via ***Window's Settings***:
```

2024-03-21 13:33 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +To uninstall Java via Mac's ***Terminal***:
```suggestion
To uninstall Java via ***Mac's Terminal***:
```

2024-03-23 17:32 UTC, onzfonz requested changes
Please do not make these changes until we discuss this further on discord.

2024-03-23 17:32 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +Uninstall any previous Java versions from your computer to avoid version conflicts.
```suggestion
*Uninstall any previous Java versions from your computer to avoid version conflicts.*
```

2024-03-23 17:32 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +- Select **Apps - Apps & features**
```suggestion
- Click ***Start***
- Select ***Settings***
- Select ***System***
- Select ***Apps - Apps & features***
```

2024-03-23 17:32 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +4. Or you can check out these instruction.
```suggestion

Or you can check out these instructions.
```

2024-03-23 17:32 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +- Double-click on the **Terminal** icon
```suggestion
- Click on the ***Finder*** icon located in your dock
- Click on the ***Utilities*** folder
- Double-click on the ***Terminal*** icon
```

2024-03-23 17:32 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +To uninstall Java via ***Window's Settings***:
```suggestion
To uninstall Java via *Window's Settings*:
```

2024-03-23 17:32 UTC, onzfonz commented on docs/labs/1-JavaEclipse.md
> +To uninstall Java via ***Mac's Terminal***:
```suggestion
To uninstall Java via *Mac's Terminal*:
```

2024-03-25 01:35 UTC, onzfonz approved these changes
LGTM

2024-03-25 01:46 UTC, merged