Update 7-Interface.md
comp129/comp55 pull request #111
Opened 2024-03-08 00:45 UTC by ramizik

Added concrete examples of using intefaces

2024-03-08 01:21 UTC, onzfonz requested changes
Please update your branch and fix the errors here.
You'll also see that someone else ended up having a discussion about interfaces.  Please make sure that this is not duplicated as well.
Also did you get this from somewhere?
This sounds very formal and not what I would expect.

I would reduce the amount that you are trying to do here and align it better with the doc.

We're going to need a few rounds of back and forth to get this approved.

2024-03-12 04:20 UTC, ramizik reviewed
Reviewed?

2024-03-12 07:47 UTC, ramizik commented
Changes were made. Thank you for extra time given

2024-03-12 15:24 UTC, onzfonz requested changes
Looking at this further, I'm a little worried that we have put in here is actually a duplicate of the information at the bottom.

Instead, I think it would be best to come up with a goals section for the lab, which explains, by the end of this lab you will learn

1.
2.
3.

That's really all that is needed instead of this section.

If you really want to do code examples, then integrate your example for what would be needed as a solution to the ToyGuitar example, instead of creating a whole new runnable portion

2025-04-15 05:21 UTC, closed without merging