4 acm lab.md matthew kunkel
comp129/comp55 pull request #116
Opened 2024-03-08 01:18 UTC by StarDusGamer

I have changed the formatting to properly show steps and bolded and bulleted important information. The less important information is greyed out but still available if desired. I made it visually appealing so your eyes wont get lost in large amounts of text.

2024-03-08 01:29 UTC, onzfonz requested changes
So in addition to fixing the issues (you can look at the animation on the assignment page on canvas to go through all of the issues)

Please also make sure that for any of the grayed out parts, you continue using the `>` sign at the beginning of each line so that it becomes easier to recognize what is in gray and what is not.
If you don't understand any of the rules that are causing errors, feel free to reach out.

2024-03-08 02:10 UTC, StarDusGamer commented
I have addressed the suggestions and all errors have been fixed

2024-03-08 04:07 UTC, StarDusGamer commented
I have added the > for every Gray Bullet

2024-03-08 05:02 UTC, StarDusGamer reviewed
Changes Implemented

2024-03-21 13:52 UTC, onzfonz requested changes
Please use the add suggestions to batch feature here @StarDusGamer and then if this is done correctly, then we can finish off the review and I can approve on the next round.

2024-03-21 13:52 UTC, onzfonz commented on docs/labs/4-ACM.md
>  from canvas and then import that file as an existing project into Eclipse,
```suggestion
1. First, download **IntroACMLab.zip** from canvas
and then import that file as an existing project into Eclipse,
```

2024-03-21 13:52 UTC, onzfonz commented on docs/labs/4-ACM.md
> +    - **The majority of imports we'll use start with "java." or "acm."**
```suggestion
    - **The majority of imports we'll use start with `java.` or `acm.`**
```

2024-03-21 13:52 UTC, onzfonz commented on docs/labs/4-ACM.md
> +     that a particular variable can no longer be changed.
```suggestion
  > While there are a couple of extra keywords here that I don't want you to worry about too much yet,
  > the ```final``` keyword is the one that is telling Java
  > that a particular variable can no longer be changed.
```

2024-03-21 13:52 UTC, onzfonz commented on docs/labs/4-ACM.md
> +1. *Let's place a rectangle at ```START_X, START_Y``` with a width of ```200```,
```suggestion
2. *Let's place a rectangle at ```START_X, START_Y``` with a width of ```200```,
```

2024-04-05 20:08 UTC, onzfonz approved these changes
LGTM

2024-04-05 20:10 UTC, merged