Git tips addition
comp129/comp55 pull request #118
Opened 2024-03-08 03:49 UTC by esamra

fixes #91

2024-03-08 04:06 UTC, onzfonz requested changes
so this acm.jar doesn't work with the latest versions of java.
Can we have you use the newer version of the jar instead?

Let's change that stuff about going to eric roberts site and I will provide you with a link to the jar that we should use, you can use this for now...

https://www.dropbox.com/scl/fi/pq2vj3eh6kjt3hq0jcckw/acm.jar?rlkey=4vuat5s13i8xv1be7lac3aeap&dl=0

Also, please add some type of scenario that says that using gradle or the empty java gradle project would be the better way to go.  I know that this is not what we normally have with github, but I would still pitch this to them as an alternative.  You should be able to see some public projects on http://github.com/comp55 that you can use for this as well.

The rest of this looks really good though!
If you can get those changes, we'll just most likely have one more round of reviews and requesting changes and then we can get to approval

2024-03-08 04:12 UTC, esamra commented
Okay I will get started on those changes right now

2024-03-09 18:25 UTC, onzfonz requested changes
Ok, lots of comments
Please look at these directions closely.
Use the add to suggestions batch feature.

You can learn more about it here
<https://docs.github.com/articles/incorporating-feedback-in-your-pull-request>
We'll probably have one more round, because I may have introduced some errors here.

2024-03-09 18:25 UTC, onzfonz commented on docs/labs/GitTips.md
> +   EclpiseMarketSpace
ideally this would be stored locally instead of via the assets url, but we'll just do that here since it's the quickest fix for the placeholder

2024-03-09 18:25 UTC, onzfonz commented on docs/labs/GitTips.md
> +   you should be good to go.
```suggestion
   All you have to do now is click on ***File -> New -> Project***
   Then in the search bar, you will enter `gradle`.
   Click on ***Gradle project***.
   Then ***enter your project name*** and click ***Next***.
   No need to override any settings, just click ***Next***.
   The project should start to load in now.
   All you need to press is ***Finish***.
   One problem that occurs is that your project at first appears inside of a lib folder,
   which makes things more complicated.
   We will leave it for now.
   However, what we will want to do is include the acm library in our *build.gradle* file.
   Using the *Project Explorer* pane, copy and paste *acm.jar*
   into your new Gradle Project's folder to the same directory as your *build.gradle* file.
   Now, add this line to the dependencies section of your *build.gradle*:
   `implementation files('acm.jar')`
   That's all that is needed for gradle to know about that file.
   Many of a build tool's benefits occur
   with having a central place to download libraries and versions.
   This allows you to merely specify as a list what you need in *build.gradle*
   and gradle will fetch the right library.
   
   As one final example, if you want to use javaFx (which is needed for the AudioPlayer class).
   You don't need to download any libraries, you merely add this line to the `plugins` section:
   `id 'org.openjfx.javafxplugin' version '0.0.13'`
   
   And then add this other set of options (shown in picture below)
   outside of any section and as its own independent section in *build.gradle*
   ![image](https://github.com/comp129/comp55/assets/239024/05289d85-1639-4993-af08-c523c6ab7521)
   Any time you make changes to your gradle project,
   Just save and ***refresh gradle project***, and wait a little bit and watch libraries
   magically appear!
   Build tools are a modern way to develop large applications
   and are good tool to know about as you code more in the future!
```

2024-03-10 02:06 UTC, esamra commented
Sorry for being late professor, I was pretty exhausted from stuff yesterday and I had work today. I resolved all of those issues. A problem I had was that the lib project was being created separately. I was trying to see how gradle worked because I do not remember making a gradle project myself in Comp 55.  But I got the gradle files all to appear in the gradle project the user created. and deleting lib. But I guess you are okay with the way the file runs like that. I put in all of the changes. If you want me I can provide more images on how to create the gradle project other wise I am ready for the review.

2024-03-10 05:38 UTC, onzfonz approved these changes
LGTM

2024-03-10 06:25 UTC, merged