Acm.md comments
comp129/comp55 pull request #119
Opened 2024-03-08 04:01 UTC by MichaelJr1

Added comments in example code so future students understand each line of code
Issue#107

2024-03-08 04:09 UTC, onzfonz requested changes
Please put the note about not making lengthy comments outside of the java file as actual text.
Do not use all caps there, but use the formatting for markdown to help with this.

I would also reword the comments for init run and main, by telling them that they really only should be changing run and init should only be about changings the sizes and main they should leave alone but that is the start of the program.

Once you make those changes we'll have one more round of changes

2024-03-08 04:34 UTC, MichaelJr1 commented
Made the changes, let me know if there is anything else that I should change

2024-03-08 05:35 UTC, onzfonz requested changes
Please use add suggestions to batch from the files changed tab.
Once this happens you may have one more round to request changes and then I would approve
make sure you use this button
![image](https://github.com/comp129/comp55/assets/239024/25e3cdb7-7902-483f-bdf0-dc6c424ff522)

you can access it from the files changed tab in the pull request.

2024-03-08 05:35 UTC, onzfonz commented on docs/labs/4-ACM.md
> +import java.awt.*; // // This imports classes for Abstract Window Toolkit (AWT) for graphics
```suggestion
// These 4 lines import necessary libraries for graphics and utilities
import acm.graphics.*; // imports classes for drawing graphics
import acm.program.*;  // imports classes for creating graphical programs
import acm.util.*;     // imports classes made to make writing programs easier
import java.awt.*;     // imports classes for Abstract Window Toolkit (AWT) for graphics
```

2024-03-08 05:35 UTC, onzfonz commented on docs/labs/4-ACM.md
> +    public static final int PROGRAM_WIDTH = 800; // This sets the Width size of the program window
```suggestion
    public static final int PROGRAM_HEIGHT = 600; // Sets the Height of the program window in pixels
    public static final int PROGRAM_WIDTH = 800; // does the same for the Width
```

2024-03-08 05:35 UTC, onzfonz commented on docs/labs/4-ACM.md
> +    // The initialization method 'init' is about changing the sizes
```suggestion
    // The method 'init' should not be changed; it is only for setting the window size
```

2024-03-08 05:35 UTC, onzfonz commented on docs/labs/4-ACM.md
> +    // This part of the program is about adding GLabels to the program
```suggestion
    // run is your starting point for your program; the code here adds GLabels to the program
```

2024-03-08 05:35 UTC, onzfonz commented on docs/labs/4-ACM.md
> +    // It is recommended to leave this part of the program alone
```suggestion
    // To abide by java's rules, we have the main method that starts the program
    // Leave this part alone; start is another method that calls init and run.
```

2024-03-08 05:35 UTC, onzfonz commented on docs/labs/4-ACM.md
> +        //This creates a new instance of the ACMLab class, it then calls its start method to begin execution
```suggestion
        // Because it is static, it creates a new instance of the ACMLab class, then calls start on it
```

2024-03-11 19:30 UTC, onzfonz approved these changes
LGTM

2024-03-11 19:32 UTC, onzfonz commented
@MichaelJr1 approved, all that is left is for you to update the branch and merge via the green button yourself

2024-03-11 20:10 UTC, merged