Koby izunaso GitHub miscellany
comp129/comp55 pull request #121
Opened 2024-03-08 05:28 UTC by Kobyizunaso

Add text with more debugging tips
Added link to detailed list of dubbing tips'
Added another way of selecting breakpoint besides the one already
Added image on how to select breakpoint

2024-03-08 05:41 UTC, onzfonz requested changes
I would remove the letters from the headings
If you want it can be another list
Also rename you breakpoint file as it has a space between the end of the name and the extension

Lastly, i would like you to break up the paragraph on lines 100 to 118 and any other text not as a hard wrap but to break it up by clauses and sentences
Any text after a period or comma typically goes on the next line down.
Please see most of the file to see how it should be formatted.
Anything that is too long to fit on one line should be broken down so that each line has a phrase that is meaningful
This makes it easier to edit in the future in meaningful ways.

2024-03-08 05:41 UTC, onzfonz commented
you also need to link to the issue correctly as the canvas assignment states @Kobyizunaso and we mention in discord

2024-03-08 05:53 UTC, Kobyizunaso commented
Updated changes you suggested and updated issue commentary.

2024-03-08 05:56 UTC, Kobyizunaso reviewed
Removed alphabets. Spaces new tip properly and spaces images for breakpoint.

2024-03-08 17:42 UTC, onzfonz requested changes
Please use the ***add suggestions to batch*** button from the files changed tab to commit the suggestions as a single commit and fix the remaining issues that I've pointed out here.

![image](https://github.com/comp129/comp55/assets/239024/085e0763-fe67-41c6-8681-373968f8aa47)

![image](https://github.com/comp129/comp55/assets/239024/a3b0bf0d-5682-423b-8b5c-d46b1a793d8e)

![image](https://github.com/comp129/comp55/assets/239024/0f9b82a1-8cdf-4319-8832-09e878a50d47)

Also again, please link the issue and use this picture to help you edit the fixes portion in the description correctly

2024-03-09 05:08 UTC, onzfonz requested changes
Please do not commit the suggestions unless the add suggestions to batch is working for you.
If you are stuck, please send a screenshot and refrain from committing or repeating the same steps.

2024-03-09 05:08 UTC, onzfonz commented on docs/labs/3-Debug.md
> +### Finding the joy in Debugging
```suggestion
### Finding the Joy in Debugging
```

2024-03-09 05:08 UTC, onzfonz commented on docs/labs/3-Debug.md
> +it feels really rewarding.
```suggestion
and making everything work smoothly again.
Just like any challenge, debugging has its difficulties,
but when you successfully fix the issues, it feels really rewarding.
```

2024-03-09 05:08 UTC, onzfonz commented on docs/labs/3-Debug.md
> +Every time developers debug, they have a chance to learn something new.
```suggestion
Every time you debug, *you have a chance to learn something new*.
```

2024-03-09 05:08 UTC, onzfonz commented on docs/labs/3-Debug.md
> +It helps them understand the system better, discover new tools,
```suggestion
Debugging helps you understand the system better, discover new tools,
```

2024-03-09 05:08 UTC, onzfonz commented on docs/labs/3-Debug.md
> +and improve their problem-solving skills.
```suggestion
and improve your problem-solving skills.
```

2024-03-21 13:54 UTC, onzfonz commented
@Kobyizunaso hope the conference is going well!  Let me know if you have any questions about following the steps outlined here so that you can be approved.

2024-03-25 01:23 UTC, onzfonz requested changes
please commit this

2024-03-25 01:23 UTC, onzfonz commented on docs/labs/3-Debug.md
> +Debugging is basically about solving problems.
```suggestion
Debugging is basically about solving problems.
```

2024-03-25 01:24 UTC, onzfonz approved these changes
LGTM

2024-03-25 01:27 UTC, merged