fixes #1
comp129/comp55 pull request #15
Opened 2023-03-06 23:02 UTC by n-bakken

fixed formatting issues in MouseEvent section

2023-03-06 23:37 UTC, onzfonz requested changes

2023-03-06 23:37 UTC, onzfonz commented on docs/labs/5-Interact.md
> +add a call to ```ball```'s `setLocation`.
```suggestion
add a call to `ball`'s `setLocation`.
```

2023-03-06 23:37 UTC, onzfonz commented on docs/labs/5-Interact.md
> +ask the ball for its x location by calling `getX()`
```suggestion
ask the ball for its `x` location by calling `getX()`
```

2023-03-06 23:37 UTC, onzfonz commented on docs/labs/5-Interact.md
>  To get the y, however,
```suggestion
To get the `y`, however,
```

2023-03-07 04:48 UTC, onzfonz requested changes
you could have used the commit suggestion.
Please also edit the description to say fixes the issue instead of the title

2023-03-07 18:14 UTC, n-bakken commented
I believe I changed the title/description accordingly, please let me know if I did this incorrectly!

2023-03-08 01:03 UTC, onzfonz requested changes
just one more, please make sure to use the commit suggestion from the pull request itself instead of commit the code from the editor

2023-03-08 01:03 UTC, onzfonz commented on docs/labs/5-Interact.md
> +add a call to `ball`s `setLocation`.
```suggestion
add a call to `ball`'s `setLocation`.
```

2023-03-08 01:15 UTC, onzfonz approved these changes

2023-03-08 01:31 UTC, merged