Add hash links & removed some wordy text
comp129/comp55 pull request #31
Opened 2023-03-08 23:40 UTC by Macro51337

2023-03-09 01:19 UTC, onzfonz requested changes
I'd also like a second opinion on lines 65-85 being wordy
I think there are some terms that I'd like folks to understand here

Namely, that hashmaps are like dictionaries
what a key and value are and how they work
and to link it back to the example

2023-03-09 01:19 UTC, onzfonz commented on docs/labs/12-Hash.md
> +Click [here](https://www.geeksforgeeks.org/differences-between-hashmap-and-hashtable-in-java/)
we aren't using geeks for geeks links (IMO it is SEO bot-fodder)

2023-03-09 01:20 UTC, onzfonz commented
you also need to edit your file so that it links your issue with the PR.  Please edit that in your description

2023-03-09 05:50 UTC, Macro51337 commented
added better links from oracle java...decided to add back lines 65-85 because they are helpful for students. couldn't find a way to make the text less wordy

2023-03-09 18:03 UTC, onzfonz requested changes
You may also just start with the hashmap link at the beginning when it first gets introduced.  That has been another way to introduce the concept and links without adding and addition sentence or you could say something like

Hashmap ([more info](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html))

2023-03-10 00:40 UTC, Macro51337 commented
made changes requested by professor

2023-03-10 01:24 UTC, onzfonz requested changes
please use commit suggestion box in the pull request on github site to commit this and I will approve it

2023-03-10 01:24 UTC, onzfonz commented on docs/labs/12-Hash.md
> +but `HashTable` is now obsolete and still available for legacy reasons.
```suggestion
but `HashTable` is now obsolete;
it is still available for legacy reasons.
```

2023-03-10 01:47 UTC, Macro51337 commented on docs/labs/12-Hash.md
> +but `HashTable` is now obsolete and still available for legacy reasons.
made changes to lines 58-59

2023-03-10 02:53 UTC, onzfonz requested changes
Please make sure that you commit this from <https://github.com/comp129/comp55/pull/31>
Otherwise, I'll request another change before approving

2023-03-10 02:53 UTC, onzfonz commented on docs/labs/12-Hash.md
> +and still available for legacy reasons.
```suggestion
it is still available for legacy reasons.
```

2023-03-10 05:01 UTC, onzfonz approved these changes

2023-03-10 05:19 UTC, merged