Added link to UML website and provided example
comp129/comp55 pull request #35
Opened 2023-03-09 03:16 UTC by Amr-mah

fixes #26

2023-03-09 03:29 UTC, onzfonz requested changes
Also did you get this example from somewhere? If so we need to cite

2023-03-09 03:29 UTC, onzfonz commented on docs/labs/61-UseCasePic.md
> +Each interaction is a use case. The diagram will identify external systems tha app needs,
```suggestion
Each interaction is a use case. The diagram will identify external systems that the app needs,
```

2023-03-09 03:29 UTC, onzfonz commented on docs/labs/61-UseCasePic.md
> +By using UML, you get a high level view and ensure the app meets user needs.
```suggestion
By using UML, you get a high-level view and ensure the app meets user needs.
```

2023-03-09 03:55 UTC, Amr-mah commented
> Also did you get this example from somewhere? If so we need to cite
I didnt get the example from somewhere

2023-03-09 18:09 UTC, onzfonz requested changes
just do these three changes via the commit suggestion on the website and we'll be good

2023-03-09 18:09 UTC, onzfonz commented on docs/labs/61-UseCasePic.md
> +If you want to learn more about UML, you can visit the official UML website here: [UML](https://www.uml.org/).
```suggestion
If you want to learn more about UML, you can visit the [official UML website](https://www.uml.org/).
```

2023-03-09 18:09 UTC, onzfonz commented on docs/labs/61-UseCasePic.md
> +Imagine you are a software developer working on a mobile banking app.
```suggestion

> Imagine you are a software developer working on a mobile banking app.
```

2023-03-09 18:09 UTC, onzfonz commented on docs/labs/61-UseCasePic.md
> +Each interaction is a use case. The diagram will identify external systems that the app needs,
```suggestion

Each interaction is a use case. The diagram will identify external systems that the app needs,
```

2023-03-10 01:25 UTC, onzfonz approved these changes

2023-03-10 02:40 UTC, merged