Update 12-Hash.md with hashmap image
comp129/comp55 pull request #40
Opened 2023-03-09 07:21 UTC by Milo-Zhao

The image is original work.

2023-03-09 07:24 UTC, Milo-Zhao commented
Fix issues #28

2023-03-09 18:28 UTC, onzfonz requested changes
Also write fixes #XX in the description of the pull request, not as part of the title

2023-03-09 18:30 UTC, onzfonz requested changes

2023-03-09 18:30 UTC, onzfonz commented on docs/labs/12-Hash.md
> +This is a picture that can help you understand hashmap more intuitively:
```suggestion
Here's a picture that may help you understand a `HashMap` more intuitively:
```

2023-03-09 21:18 UTC, Milo-Zhao commented on docs/labs/12-Hash.md
> +This is a picture that can help you understand hashmap more intuitively:
I can do that!

2023-03-09 22:35 UTC, onzfonz commented
Edit the place that says this image is original work at the top of the pull request, just below the title

2023-03-10 00:45 UTC, onzfonz approved these changes

2023-03-10 00:46 UTC, merged