67 add media
comp129/comp55 pull request #58
Opened 2023-03-10 06:36 UTC by nfantinodyer

fixes #52

2023-03-10 17:35 UTC, onzfonz requested changes
please rename the files something closer to what they represent, something like basic_plantuml_diagram or something along those lines

Please also change the text description inside of the brackets for the pictures

2023-03-10 23:23 UTC, nfantinodyer commented
Changes have been addressed

2023-03-11 02:56 UTC, onzfonz requested changes
Just approve these two from the pull request conversation page and you should be good

2023-03-11 02:56 UTC, onzfonz commented on docs/labs/67-Sequence.md
> +![advanced_plantuml_diagram](lab67media/advanced_plantuml_diagram.png)
```suggestion
![advanced sequence diagram with alt and else](lab67media/advanced_plantuml_diagram.png)
```

2023-03-11 02:56 UTC, onzfonz commented on docs/labs/67-Sequence.md
> +![basic_plantuml_diagram](lab67media/basic_plantuml_diagram.png)
```suggestion
![basic sequence diagram](lab67media/basic_plantuml_diagram.png)
```

2023-05-05 23:08 UTC, onzfonz commented
@nfantinodyer can you approve these two requests so that this can be merged?

2023-05-05 23:36 UTC, nfantinodyer commented
@onzfonz It says I'm unable to approve the changes as its my pull request, so I clicked on the resolve conversation button for those two changes instead.
![image](https://user-images.githubusercontent.com/89417141/236584974-c1c08fc0-0d57-413c-86b5-334fc85742fd.png)

2023-05-06 02:36 UTC, onzfonz commented
In the conversation it should show the suggestions and say commit suggestion

2023-05-06 02:41 UTC, nfantinodyer commented
@onzfonz I found it thank you

2024-03-02 17:22 UTC, closed without merging