Addendum to 8 GitHub prep.md
comp129/comp55 pull request #63
Opened 2023-03-10 21:00 UTC by bayers1

Accidentally closed the previous pull request.

2023-03-10 22:18 UTC, onzfonz requested changes
Please separate based on sentences so that new sentences start on a new line.
Please also make sure that you put fixes # and your issue in the pull request description @bayers1

2023-03-11 01:00 UTC, bayers1 commented
Sentences have been readjusted and the issue is now listed.

2023-03-11 02:02 UTC, onzfonz commented
you need to remove the word issue from the description

2023-03-11 02:15 UTC, onzfonz requested changes
please commit via commit suggestions

2023-03-11 02:15 UTC, onzfonz commented on docs/labs/8-Github-Prep.md
> +will no longer be visible.***
```suggestion
Be sure that you have saved this token, as once you leave the generation page,
***the token will no longer be visible***.
```

2024-03-02 17:24 UTC, closed without merging