Fixes #77
comp129/comp55 pull request #95
Opened 2024-03-06 22:25 UTC by K5741

2024-03-06 23:22 UTC, onzfonz commented
@K5741 need to use the `fixes` language specified in the assignment and fix the errors.  Please revisit https://pacific.instructure.com/courses/117102/assignments/558259 before I review it.

2024-03-07 00:45 UTC, K5741 commented
> @K5741 need to use the `fixes` language specified in the assignment and fix the errors. Please revisit https://pacific.instructure.com/courses/117102/assignments/558259 before I review it.

2024-03-07 00:54 UTC, onzfonz commented
checks pass but the title should not have the fixes it should be in the description, please see #10 for clues on how to do this part.  Once this is there you can re-request review

2024-03-07 05:09 UTC, onzfonz commented
@K5741 the branch needs to be updated and fixes still needs to be added to the description, not in the title, please see #10 before I can review

2024-03-07 05:10 UTC, onzfonz requested changes
please see comments about #10 that I left before I will review here), but also the brackets notation is not how we would do any commands, please use the arrow syntax `->` and use triple stars `***` to enclose any eclipse menu commands.

2024-03-08 04:17 UTC, onzfonz requested changes
please use the add suggestions to batch to get this to work, which must be done from the files changed tab on the pull request.

you'll do this from the files changes.  You still need to also edit the description

![image](https://github.com/comp129/comp55/assets/239024/646c6439-d47e-4a6b-9844-bf1265f6b03f)

![image](https://github.com/comp129/comp55/assets/239024/9bd8b60f-c7fd-4bad-8ac1-2f4d3ff9c89e)

2024-03-08 04:17 UTC, onzfonz commented on docs/labs/GitTips.md
> +remote repository with the new changes.
```suggestion
  are ready to be pushed into the program.
  Pushing the commit then updates the remote repository with the new changes.
```

2024-03-08 04:17 UTC, onzfonz commented on docs/labs/GitTips.md
> +By dragging all unstaged changes to staged and then committing, you are ensuring that your local changes
```suggestion
  By dragging all unstaged changes to staged and then committing, your local changes
```

2024-03-08 04:17 UTC, onzfonz commented on docs/labs/GitTips.md
> +project and the changes you've pulled.
```suggestion
  This ensures that the pull is being recognized as source code by the IDE,
  allowing them to be compiled and executed correctly.
  This step helps in maintaining consistency between the working project
  and the changes you've pulled.
```

2024-03-08 04:17 UTC, onzfonz commented on docs/labs/GitTips.md
> +to ensure that the project's dependencies are correctly synchronized.
```suggestion
   - ***Gradle -> Refresh Gradle***
  Sometimes, after pulling changes from the program, the Gradle configuration might need to be refreshed
  to ensure that the project's dependencies are correctly synchronized.
```

2024-03-08 17:32 UTC, onzfonz commented
@K5741 you still need to update your branch and follow the add suggestions to batch information here

2024-03-09 02:40 UTC, onzfonz requested changes
let's try the request changes add to batch feature one more time @K5741

2024-03-09 02:40 UTC, onzfonz commented on docs/labs/GitTips.md
> +5. If you are having project issues after a pull:
```suggestion
5. If you're having project issues after a pull, try:
```

2024-03-09 02:40 UTC, onzfonz commented on docs/labs/GitTips.md
> + to ensure that the project's dependencies are correctly synchronized.
```suggestion
    Sometimes, after pulling changes from the program, the Gradle configuration might need to be refreshed
    to ensure that the project's dependencies are correctly synchronized.
```

2024-03-09 02:40 UTC, onzfonz commented on docs/labs/GitTips.md
> + and the changes you've pulled.
```suggestion
    This ensures that the pull is being recognized as source code by the IDE,
    allowing them to be compiled and executed correctly.
    This step helps in maintaining consistency between the working project
    and the changes you've pulled.
```

2024-03-09 02:40 UTC, onzfonz commented on docs/labs/GitTips.md
> + Pushing the commit then updates the remote repository with the new changes.
```suggestion
    By dragging all unstaged changes to staged and then committing, your local changes
    are ready to be pushed into the program.
    Pushing the commit then updates the remote repository with the new changes.
```

2024-03-09 05:02 UTC, onzfonz requested changes
do not commit unless you see the add suggestions to batch button enabled in the files changed tab and then after clicking all three you click the commit suggestions button (just once)
Please verify with a screenshot

2024-03-09 05:02 UTC, onzfonz commented on docs/labs/GitTips.md
> +    to ensure that the project's dependencies are correctly synchronized.
```suggestion
     Sometimes, after pulling changes from the program, the Gradle configuration might need to be refreshed
     to ensure that the project's dependencies are correctly synchronized.
```

2024-03-09 05:02 UTC, onzfonz commented on docs/labs/GitTips.md
> +    and the changes you've pulled.
```suggestion
     This ensures that the pull is being recognized as source code by the IDE,
     allowing them to be compiled and executed correctly.
     This step helps in maintaining consistency between the working project
     and the changes you've pulled.
```

2024-03-09 05:02 UTC, onzfonz commented on docs/labs/GitTips.md
> +    Pushing the commit then updates the remote repository with the new changes.
```suggestion
     By dragging all unstaged changes to staged and then committing, your local changes
     are ready to be pushed into the program.
     Pushing the commit then updates the remote repository with the new changes.
```

2024-03-09 05:12 UTC, onzfonz approved these changes
LGTM

2024-03-09 05:12 UTC, onzfonz commented
Now all you have to do is update the branch and then you'll be able to merge

2024-03-09 05:18 UTC, merged